In [1]:
import torch
import torch.nn as nn

from torch.nn import functional as F

import time
import numpy as np


In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-92,  13, -62,   4, -69, -39])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2, 3)
input

tensor([[0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.8960e+24, 3.0805e-41]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2, 3), dtype=torch.int64)
emptylike = torch.empty_like(a)
emptylike

tensor([[ 94417922843456,  94417977307760, 140057658314320],
        [              1,               5,               0]])

In [12]:
%%time
start_time = time.time()

# matrix operations
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time =  end_time - start_time
print(f'{elapsed_time:.10f}')

0.0001966953
CPU times: user 235 µs, sys: 236 µs, total: 471 µs
Wall time: 433 µs


In [13]:
%%time
torch_rand1 = torch.rand(100, 100, 100, 100)
torch_rand2 = torch.rand(100, 100, 100, 100)
np_rand1 = torch.rand(100, 100, 100, 100) 
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time =  end_time - start_time
print(f'{elapsed_time:.10f}')

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time =  end_time - start_time
print(f'{elapsed_time:.10f}')


0.8750627041
4.6055519581
CPU times: user 2.44 s, sys: 28.6 s, total: 31 s
Wall time: 25.2 s


In [14]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])


In [15]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0) # vertical 
out

tensor([1, 2, 3, 4, 5])

In [16]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [18]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [21]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
                       
# Stack de tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-1.4950,  0.3772,  5.8671], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)
print(softmax_output.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [24]:
# Initialize an embedding layer
vocab_size  = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor fo shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embbeding vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [25]:
# viavel mult de matrizes = coluna da primeira == linha da outra
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [26]:
# não é possível multiplicar 2 matrizes com tipos de dados diferentes
int_64 = torch.randint(1, (3, 2)).float()
# type int64
float_32 = torch.rand(2, 3)
# type float32
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [40]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)
print(a)

2 3 5
torch.Size([2, 3, 5])
tensor([[[0.8334, 0.6632, 0.6963, 0.6984, 0.5635],
         [0.4649, 0.9334, 0.7066, 0.5147, 0.1702],
         [0.9315, 0.2727, 0.0087, 0.6948, 0.1256]],

        [[0.8511, 0.4671, 0.7531, 0.7027, 0.3098],
         [0.8250, 0.5694, 0.6363, 0.3903, 0.1567],
         [0.9853, 0.1083, 0.5856, 0.6298, 0.7608]]])


In [14]:
# Activation functions in pytorch
x = torch.tensor([-0.05], dtype=torch.float32)

y = F.relu(x)
print(y)
y = F.sigmoid(x) # 0 and 1
print(y)
y = F.tanh(x) # -1 and 1
print(y)

tensor([0.])
tensor([0.4875])
tensor([-0.0500])


In [ ]:
ß